baseurl      = "https://n-jacobson.com"
title        = "Welcome to my site"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "My name is Nathan Jacobson."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Nathan Jacobson's site"
  keywords = "homepage, personal"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello, welcome here"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "My name is Nathan. I'm a student at RRC Polytech in the Cyber Security program. I'm really interested in Information Security and find the whole field extremly interesting. In my free time I like to mess around with my server at home and try different selfhosted software out."

    [languages.en.params.logo]
      logoText = "Hello"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/about"

  # and submenus
  [[menu.main]]
    identifier  = "resume"
    name        = "Resume"
    url         = "/resume"



 [[params.social]]
   name = "linkedin"
   url = "https://www.linkedin.com/in/nathan-jacobson-87660b32a/"

 [[params.social]]
   name = "signal"
   url = "https://signal.me/#eu/usINd636F4D4Wm1RfNxHSKTYhxYgUds8TapG7n-ITDD92Z2UvgBLi6QuBrZMiG7w"

 [[params.footer]]
   bottomText = "mailto:nathan@n-jacobson.com"
